# @package _group_

common:
  fp16: true
  log_format: json
  log_interval: 200
  tensorboard_logdir: tblog
  seed: 1337
  user_dir: ???

checkpoint:
  save_interval: 1
  keep_interval_updates: 1
  no_epoch_checkpoints: true
  best_checkpoint_metric: accuracy
  maximize_best_checkpoint_metric: true
  

distributed_training:
  ddp_backend: no_c10d
  find_unused_parameters: false
  distributed_world_size: 8
  #distributed_port: 29671
  nprocs_per_node: 8

task:
  _name: unit_pretraining
  is_s2s: true
  data: ???
  label_dir: ???
  tokenizer_bpe_model: ???
  normalize: true  # must be consistent with pre-training
  labels: ["wrd"]
  single_target: true
  fine_tuning: true
  stack_order_audio: 4
  tokenizer_bpe_name: sentencepiece
  max_sample_size: 600
  modalities: ["video", "audio"]
  image_aug: true
  pad_audio: true
  random_crop: false

dataset:
  num_workers: 3
  max_tokens: 3000
  validate_after_updates: 0
  validate_interval: 1
  train_subset: train
  valid_subset: test

criterion:
  _name: label_smoothed_cross_entropy_with_joint_ctc
  report_accuracy: true
  label_smoothing: 0.1

optimization:
  max_update: 60000
  lr: [0.001]
  sentence_avg: true
  update_freq: [4]

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-08

lr_scheduler:
  _name: tri_stage
  warmup_steps: 15000
  hold_steps: 0
  decay_steps: 45000
  final_lr_scale: 0.05

model:
  _name: utut_model
  w2v_path: ???
  apply_mask: false
  mask_selection: static
  mask_length: 10
  mask_other: 0
  mask_prob: 0.75
  mask_channel_selection: static
  mask_channel_length: 64
  mask_channel_other: 0
  mask_channel_prob: 0.5
  layerdrop: 0.1
  dropout: 0.0
  activation_dropout: 0.1
  attention_dropout: 0.0
  feature_grad_mult: 1.0
  decoder_layers: 6
  decoder_dropout: 0.1
  decoder_attention_dropout: 0.0
  decoder_activation_dropout: 0.1
  masking_updates: 60000
  share_decoder_input_output_embed: true
  decoder_normalize_before: true
  decoder_embed_dim: 1024
  decoder_ffn_embed_dim: 4096
  decoder_attention_heads: 8
  progressive_masking: true
  
hydra:
  job:
    config:
      override_dirname:
        kv_sep: '-'
        item_sep: '__'
        exclude_keys:
          - run
          - task.data
          - task.label_dir
          - model.w2v_path
          - dataset.train_subset
          - dataset.valid_subset
          - criterion.wer_kenlm_model
          - criterion.wer_lexicon
  run:
    dir: ???
  sweep:
    dir: ???
    subdir: ${hydra.job.config_name}__${hydra.job.override_dirname}
